services:
  monitor-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    container_name: monitor-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_LOG_API_URL=${REACT_APP_LOG_API_URL}
    networks:
      - proxy

networks:
  proxy:
    external: true  