services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_APP_LOG_API_URL
    expose:
      - "80"
    container_name: greact-drill-monitor-${BRANCH}
    environment:
      - NODE_ENV=production
      - VITE_APP_LOG_API_URL=${VITE_APP_LOG_API_URL}
    networks:
      - proxy

networks:
  proxy:
    external: true